name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发 
  workflow_dispatch:  # 允许手动触发
 
jobs:
  build:
    runs-on: windows-latest  # 必须使用Windows环境 
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pywin32
        pip install -r requirements.txt 
 
    - name: Build with PyInstaller
      run: |
        # 创建版本文件 
        echo "VERSION=$(date +%Y%m%d.%H%M)" >> $GITHUB_ENV 
        
        # 执行打包 
        pyinstaller --onefile --windowed \
          --add-data "config;config" \
          --add-data "src/web/static;static" \
          --add-data "src/web/templates;templates" \
          --icon=assets/icon.ico  \
          --name CryptoTrader-${{ env.VERSION }} \
          src/main.py  
 
    - name: Upload artifact 
      uses: actions/upload-artifact@v3 
      with:
        name: CryptoTrader-Windows 
        path: |
          dist/CryptoTrader-${{ env.VERSION }}.exe 
          config/
          static/
          templates/