name: Build Windows Executable 
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows
    runs-on: windows-2022 
 
    permissions:
      contents: write 
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.15.0 
        pip install pywin32==311 requests==2.31.0 websockets==12.0 
 
    - name: Prepare build environment 
      shell: pwsh 
      run: |
        # 创建必要的包结构
        if (-not (Test-Path "src/__init__.py")) { New-Item -Path "src/__init__.py" -ItemType File }
        if (-not (Test-Path "src/core/__init__.py")) { New-Item -Path "src/core/__init__.py" -ItemType File }
        if (-not (Test-Path "src/api/__init__.py")) { New-Item -Path "src/api/__init__.py" -ItemType File }
 
        # 确保主入口文件存在
        if (-not (Test-Path "src/core/cli.py"))  {
          @'
from src.core.strategy.base  import run_default_strategy 
from src.api.binance_futures  import BinanceAPI 
 
def main():
    run_default_strategy(BinanceAPI())
 
if __name__ == "__main__":
    main()
'@ | Out-File -FilePath "src/core/cli.py"  -Encoding ASCII
        }
 
    - name: Build executable 
      shell: pwsh 
      run: |
        pyinstaller --onefile --noconsole --clean `
          --paths src `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --name CryptoTrader `
          src/core/cli.py  
 
    - name: Verify build
      shell: pwsh
      run: |
        if (-not (Test-Path "dist/CryptoTrader.exe"))  {
          Write-Output "::error::Build failed - executable not found"
          exit 1 
        }
 
    - name: Upload artifact 
      uses: actions/upload-artifact@v4 
      with:
        name: CryptoTrader-Windows 
        path: dist/CryptoTrader.exe  
        retention-days: 7 