name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows 
    runs-on: windows-2022
 
    permissions:
      contents: write
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Verify project structure
      shell: pwsh
      run: |
        # 单行检查目录结构 
        if (-not (Test-Path "src/core")) { Write-Output "::error::Missing src/core directory"; exit 1 }
        if (-not (Test-Path "config")) { Write-Output "::error::Missing config directory"; exit 1 }
        if (-not (Test-Path "assets/icon.ico"))  { Write-Output "::error::Missing icon file"; exit 1 }
 
        # 单行创建入口文件 
        if (-not (Test-Path "src/core/cli.py"))  {
          Write-Output "from src.core.strategy.base  import run_default_strategy" > src/core/cli.py  
          Write-Output "from src.api.binance_futures  import BinanceAPI" >> src/core/cli.py  
          Write-Output "if __name__ == '__main__': run_default_strategy(BinanceAPI())" >> src/core/cli.py 
        }
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.15.0 pywin32==311 requests==2.31.0 websockets==12.0
 
    - name: Build executable 
      shell: pwsh 
      run: |
        $root = (Get-Item -Path ".\").FullName 
        pyinstaller --onefile --clean `
          --add-data "$root/config;config" `
          --add-data "$root/src/web/static;static" `
          --add-data "$root/src/web/templates;templates" `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --icon "$root/assets/icon.ico"  `
          --name CryptoTrader `
          "$root/src/core/cli.py" 
 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CryptoTrader-Windows
        path: dist/CryptoTrader.exe 
        retention-days: 7 