name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows 
    runs-on: windows-2022
 
    permissions:
      contents: write
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.15.0 pywin32==311
        pip install aiohttp==3.9.3 requests==2.31.0 websockets==12.0 
        
        # 仅当pyproject.toml 格式正确时才安装项目 
        if [ -f pyproject.toml  ]; then
          pip install -e .
        fi 
 
    - name: Build executable
      shell: pwsh
      run: |
        pyinstaller --onefile --noconsole --clean `
          --paths src `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --hidden-import aiohttp `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --name CryptoTrader `
          src/core/cli.py  
 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CryptoTrader-Windows
        path: dist/CryptoTrader.exe 
        retention-days: 7