name: Build Windows Executable 
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows
    runs-on: windows-2022 
 
    permissions:
      contents: write 
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
 
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.15.0 pywin32==311
        pip install requests==2.31.0 websockets==12.0 
 
    - name: Fix imports and build 
      shell: pwsh 
      run: |
        # 创建必要的包结构 
        if (!(Test-Path "src/__init__.py")) { "" > "src/__init__.py" }
        if (!(Test-Path "src/core/__init__.py")) { "" > "src/core/__init__.py" }
        if (!(Test-Path "src/api/__init__.py")) { "" > "src/api/__init__.py" }
 
        # 修改cli.py 使用绝对导入 
        @"
from src.core.strategy.base  import run_default_strategy 
from src.api.binance_futures  import BinanceAPI 
 
def main():
    run_default_strategy(BinanceAPI())
 
if __name__ == '__main__':
    main()
"@ > src/core/cli.py  
 
        # 构建命令 
        pyinstaller --onefile --noconsole --clean `
          --paths src `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --name CryptoTrader `
          src/core/cli.py  
 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CryptoTrader-Windows
        path: dist/CryptoTrader.exe 
        retention-days: 7