name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows 
    runs-on: windows-2022
 
    permissions:
      contents: write
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install pyinstaller==6.15.0 pywin32==311 
        pip install pandas==2.1.4 aiohttp==3.9.3 requests==2.31.0 websockets==12.0
 
    - name: Build executable 
      shell: pwsh 
      run: |
        # 确保使用绝对路径 
        $root = (Get-Item -Path ".").FullName
        
        pyinstaller --onefile --noconsole --clean `
          --paths "$root/src" `
          --add-data "$root/config;config" `
          --add-data "$root/src/web/static;static" `
          --add-data "$root/src/web/templates;templates" `
          --hidden-import pandas `
          --hidden-import aiohttp `
          --hidden-import src.core.strategy.base  `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --name CryptoTrader `
          "$root/src/core/cli.py" 
 
    - name: Upload artifact 
      uses: actions/upload-artifact@v4 
      with:
        name: CryptoTrader-Windows 
        path: dist/CryptoTrader.exe  
        retention-days: 7 