name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows 
    runs-on: windows-2022
 
    permissions:
      contents: write
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Verify project structure
      shell: pwsh
      run: |
        # Check for required directories 
        $requiredDirs = "src/api", "src/core", "config"
        $missing = $requiredDirs | Where-Object { -not (Test-Path $_) }
        if ($missing) { 
          Write-Output "Missing directories: $($missing -join ', ')"
          exit 1 
        }
 
        # Create entry point if needed 
        if (-not (Test-Path "src/core/cli.py"))  {
          Write-Output "Creating temporary entry point..."
          $entryScript = @'
from src.core.strategy.base  import run_default_strategy
from src.api.binance_futures  import BinanceAPI
 
if __name__ == "__main__":
    run_default_strategy(BinanceAPI())
'@ 
          $entryScript | Out-File -FilePath "src/temp_entry.py"  -Encoding ASCII
          $entry = "src/temp_entry.py" 
        } else {
          $entry = "src/core/cli.py" 
        }
        echo "ENTRY_POINT=$entry" >> $env:GITHUB_ENV
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pywin32
        pip install -e .
 
    - name: Build executable 
      shell: pwsh 
      run: |
        pyinstaller --onefile --noconfirm --clean `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --icon assets/icon.ico  `
          --name CryptoTrader `
          $env:ENTRY_POINT
 
    - name: Upload artifact 
      uses: actions/upload-artifact@v4 
      with:
        name: CryptoTrader-Windows 
        path: dist/CryptoTrader.exe  
        retention-days: 3 