name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows 
    runs-on: windows-2022
 
    permissions:
      contents: write
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Verify project structure
      shell: pwsh
      run: |
        # 单行检查目录结构 
        if (-not (Test-Path "src/core")) { Write-Output "::error::Missing src/core directory"; exit 1 }
        if (-not (Test-Path "config")) { Write-Output "::error::Missing config directory"; exit 1 }
 
        # 创建入口文件 (单行if语句)
        if (-not (Test-Path "src/core/cli.py"))  {
          Write-Output "from src.core.strategy.base  import run_default_strategy" > src/temp_entry.py  
          Write-Output "from src.api.binance_futures  import BinanceAPI" >> src/temp_entry.py  
          Write-Output "if __name__ == '__main__': run_default_strategy(BinanceAPI())" >> src/temp_entry.py 
          echo "ENTRY_POINT=src/temp_entry.py"  >> $env:GITHUB_ENV
        } else {
          echo "ENTRY_POINT=src/core/cli.py"  >> $env:GITHUB_ENV
        }
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pywin32
        pip install -e .
 
    - name: Build executable 
      shell: pwsh 
      run: |
        pyinstaller --onefile --clean `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --icon assets/icon.ico  `
          --name CryptoTrader `
          $env:ENTRY_POINT
 
    - name: Upload artifact 
      uses: actions/upload-artifact@v4 
      with:
        name: CryptoTrader-Windows 
        path: dist/CryptoTrader.exe  
        retention-days: 3 