name: Build Windows Executable
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows 
    runs-on: windows-2022
 
    permissions:
      contents: write
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
 
    - name: Verify requirements.txt 
      shell: pwsh
      run: |
        if (!(Test-Path "requirements.txt"))  {
          Write-Output "pyinstaller>=6.0.0" > requirements.txt 
          Write-Output "pywin32>=300" >> requirements.txt  
        }
        Get-Content requirements.txt  
 
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt  
 
    - name: Build executable
      shell: pwsh
      run: |
        $version = Get-Date -Format "yyyyMMdd.HHmm"
        echo "VERSION=$version" >> $env:GITHUB_ENV 
        pyinstaller --onefile --noconfirm --clean `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --icon=assets/icon.ico  `
          --name "CryptoTrader-$env:VERSION" `
          src/main.py 
 
    - name: Upload artifacts 
      uses: actions/upload-artifact@v4 
      with:
        name: CryptoTrader-Windows 
        path: dist/CryptoTrader-${{ env.VERSION }}.exe 
        retention-days: 3 