name: Build Windows Executable 
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
 
jobs:
  build:
    name: Build on Windows
    runs-on: windows-2022 
 
    permissions:
      contents: write 
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
 
    - name: Verify project structure 
      shell: pwsh 
      run: |
        $required = "src/core/cli.py",  "assets/icon.ico",  "config"
        $missing = $required | Where-Object { -not (Test-Path $_) }
        if ($missing) { 
          Write-Output "::error::Missing files: $($missing -join ', ')"
          exit 1 
        }
 
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install pyinstaller==6.15.0 pywin32==311 pillow==10.3.0
        pip install requests==2.31.0 websockets==12.0 
 
    - name: Convert icon format 
      shell: pwsh 
      run: |
        python -c "from PIL import Image; img = Image.open('assets/icon.ico');  img.save('assets/converted.ico',  format='ICO')" 
        if (-not (Test-Path "assets/converted.ico"))  {
          Copy-Item -Path "assets/icon.ico"  -Destination "assets/converted.ico" 
        }
 
    - name: Build executable
      shell: pwsh
      run: |
        pyinstaller --onefile --clean `
          --add-data "config;config" `
          --add-data "src/web/static;static" `
          --add-data "src/web/templates;templates" `
          --hidden-import src.api.binance_futures  `
          --hidden-import src.api.okx_futures  `
          --hidden-import src.core.strategy.base  `
          --icon "assets/converted.ico"  `
          --name CryptoTrader `
          src/core/cli.py  
 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CryptoTrader-Windows
        path: dist/CryptoTrader.exe 
        retention-days: 7